[package]
name = "oxsync"
version = "0.1.0"
edition = "2021"
authors = ["Jules Tanguy"]
license = "MIT"
description = "oxsync is a file synchronization tool with a focus on 'watch for changes' feature. It enables fast, local reads with a remote filesystem"
repository = "https://github.com/JulesTanguy/oxsync/"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
futures = "0.3.28"
indicatif = "0.17.7"
notify = "6.1.1"
tokio = { version = "1.33.0", features = ["full"] }
walkdir = "2.4.0"

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = 3 # With all optimizations
strip = true # Remove debug symbols
