[package]
name = "oxsync"
version = "0.3.0"
edition = "2024"
authors = ["Jules Tanguy"]
license = "MIT"
description = "oxsync is a file synchronization tool. It enables fast, local reads with a remote filesystem"
repository = "https://github.com/JulesTanguy/oxsync/"

[dependencies]
blake3 = "1.8"
clap = { version = "4.5", features = ["derive"] }
lru = "0.18"
notify = "8.2.0"
time = { version = "0.3.47", features = ["formatting", "alloc", "local-offset"] }
tokio = { version = "1.50", features = ["fs", "io-util", "sync", "rt-multi-thread", "macros", "time"] }
tokio-stream = { version = "0.1.18", default-features = false }

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = 3 # With all optimizations
strip = true # Remove debug symbols
